### ISSUE TITLE
ONNX support

### ISSUE THREAD

**Issue by vm7608** [KupynOrest/head_detector#10]
Can you provide ONNX models/or convert to ONNX scripts and inference code examples? I want to integrate VGGHead to my pipeline but the model weights must be in ONNX format. I have tried to convert the weights to ONNX format but it doesn't work :'( 

I appreciate your work on this project. Thank you very much!

**Comment by taesiri** [comment]
+1

**Comment by KupynOrest** [comment]
https://github.com/KupynOrest/head_detector/pull/14

https://huggingface.co/okupyn/vgg_heads/blob/main/vgg_heads_l.onnx

**Comment by taesiri** [comment]
Thanks @KupynOrest  for providing the ONNX file. I've made a [Google Colab](https://colab.research.google.com/drive/1EJn9dPdlX2qIWrZok9LF185ZJwAGOr9Y?usp=sharing) to load this model and do inference with it.
