### ISSUE TITLE
export as mesh

### ISSUE THREAD

**Issue by GuyARoss** [KupynOrest/head_detector#11]
simple/ supported way to export the head detector prediction results as a mesh?  ideally as an obj.

**Comment by claussteinmassl** [comment]
+1 for this request. Ideally the mesh would have proper UVs.

**Comment by emlcpfx** [comment]
https://github.com/KupynOrest/head_detector/issues/4

**Comment by KupynOrest** [comment]
Added the support for .obj export - https://github.com/KupynOrest/head_detector/pull/17
