### ISSUE TITLE
How about the method compared with EMOCA/MICA

### ISSUE THREAD

**Issue by xg-chu** [KupynOrest/head_detector#15]
Thanks for your excellent method and code. ^_^
Is there any comparison between this method and methods such as EMOCA or MICA in flame parameter estimation? 
If there is no quantitative comparison, which one do you think is better or stable?

**Comment by KupynOrest** [comment]
The EMOCA or MICA is designed for detailed 3D face reconstruction so should work better for cases where detailed head crops are provided. Note it also requires a tight crop.
Our method was designed for coarse estimation and to reconstruct multiple meshes in a single step. We believe that superior alignment provided by predictions from our method - https://github.com/KupynOrest/head_detector/pull/17 can also be used as the 1st stage of a more detailed 3D face regressor.

**Comment by xg-chu** [comment]
The alignment part is really great! 🚀
