### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by emlcpfx** [KupynOrest/head_detector#24]
I'm checking out the dataset, and I see there's a large and a small folder. The annotations in the small folder contain landmark and 3D vertex data, but the large folder just has the bboxes and the 3DMM params.

What's the intention there? Why doesn't the large folder have the 2D landmark data too?

**Comment by KupynOrest** [comment]
Hi, the reason of large folder containing only the 3DMM params is the dataset size. Storing all landmarks locations for all heads in a million of images would exponentially increase the size of the data.
All the additional information such as 3D/2D landmarks or head pose can be computed directly form 3DMM. In fact, for training our data loader does internally convert the 3DMM labels to ground truth if no gt landmarks are available so you can reuse this logic.

https://github.com/KupynOrest/head_detector/blob/main/yolo_head_training/yolo_head/dataset_parsing.py#L170

**Comment by emlcpfx** [comment]
Perfect, makes so much sense now. Thank you.
