### ISSUE TITLE
Request for OBJ File Exporting

### ISSUE THREAD

**Issue by Aut0matas** [KupynOrest/head_detector#4]
Hi,
Thank you for this amazing project! It has been incredibly useful for generating 3D models from 2D portraits. However, I noticed that currently the project only supports exporting the modeling result as an image.
It would be extremely helpful if you could add a feature to export the 3D model as an OBJ file. Thank you for considering this request.

**Comment by KupynOrest** [comment]
Hi, thanks for the suggestion, we didn't consider that before, but will consider adding in one of the few next releases

**Comment by mjalb** [comment]
odd to read that "Aut0matas" says "it has been ... useful for generating 3d models" ... if they then say the code only supports 2d (which is true). :-) 

That said, all the data is there. You only need to write the vertices from the head(s) you get from the predictor and add the list of triangles you can grab from the flame. Straight forward - and it works off the bat.

**Comment by mjalb** [comment]
if you want to write out a simple obj from the detection's first head, you can do that following this code outline (I am doing it this way and it works, this fragment is stripped down from my test  bundle):

```
predictions = detector(image_path)
firstHead=predictions.heads[0].vertices_3d
triangles = np.load("path/to/full_faces.npy")
f=open("output.obj","w")
for vert in firstHead:
	f.write("v "+str(vert[0])+" "+str(vert[1])+" "+str(vert[2])+"\n")
for tri in triangles:
	f.write("f "+str(tri[0]+1)+" "+str(tri[1]+1)+" "+str(tri[2]+1)+"\n")
f.close()

```
Note that this is the worst way of writing an obj (the slowest) and it does not cater for UV or vertex color, but all the info about those is in the repository as well, you just have to read the code really.

**Comment by andupotorac** [comment]
Thanks, will try to use this!
