### ISSUE TITLE
Demo locally available

### ISSUE THREAD

**Issue by yvrjsharma** [KupynOrest/head_detector#5]
It would be great to have [the official huggingface demo](https://huggingface.co/spaces/okupyn/vgg_heads) available locally in the repository and linked in the readme. This improves the accessibility and discoverability of the project for the community. 
For example, the locally available demo on the LivePortrait repository, [here](https://github.com/KwaiVGI/LivePortrait?tab=readme-ov-file#4-gradio-interface-).
![image](https://github.com/user-attachments/assets/3ac782b5-d5d4-467f-bcfb-8932b719e2b3)

**Comment by BloodAxe** [comment]
You mean this https://huggingface.co/spaces/okupyn/vgg_heads?

**Comment by yvrjsharma** [comment]
yup!

**Comment by KupynOrest** [comment]
https://github.com/KupynOrest/head_detector/pull/13

added in the last PR
