### ISSUE TITLE
Sim3DR/lib missing

### ISSUE THREAD

**Issue by dcetin** [KupynOrest/head_detector#8]
Setup script fails as it can't find the files under `./head_detector/Sim3DR/lib`, the folder seems to be missing from the repo at the moment.

Related part of the error is as follows:
`ValueError: './head_detector/Sim3DR/lib/rasterize.pyx' doesn't match any files`

**Comment by jaswin90** [comment]
I am also facing the same issue. What to do ?

**Comment by jaswin90** [comment]
@dcetin I downloaded it from original Sim3DR git repo and placed it at the corresponding folder, then it worked.

**Comment by dcetin** [comment]
Hey @jaswin90, thanks for the help. I also noticed the [PR#6](https://github.com/KupynOrest/head_detector/pull/6) now, closing this issue.
