### ISSUE TITLE
Bad result for  eye closed

### ISSUE THREAD

**Issue by lxy2017** [KupynOrest/head_detector#9]
![截屏2024-08-14 11 20 12](https://github.com/user-attachments/assets/da144f91-034c-4ba4-a6b0-541c0b031dc9)

**Comment by BloodAxe** [comment]
Thanks for pointing this up. This looks like a OOD example to me. Our training set does not contain images with faces that are larger than a whole image. So I think it is not a problem with closed eyes but rather with the fact that only a half of the face is visible. I think you should get much better results if you ensure that whole face fits the picture frame.
